// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// SRMPLE
SEXP SRMPLE(arma::vec X, arma::vec de, arma::mat Z, arma::vec betaini, int k, double tol, int maxiter);
RcppExport SEXP _coxnpgsjs_SRMPLE(SEXP XSEXP, SEXP deSEXP, SEXP ZSEXP, SEXP betainiSEXP, SEXP kSEXP, SEXP tolSEXP, SEXP maxiterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type de(deSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type betaini(betainiSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    rcpp_result_gen = Rcpp::wrap(SRMPLE(X, de, Z, betaini, k, tol, maxiter));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_coxnpgsjs_SRMPLE", (DL_FUNC) &_coxnpgsjs_SRMPLE, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_coxnpgsjs(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
